version: "3.8"
services:
    server:
        build:
            context: ./
            dockerfile: ./server.Dockerfile
        image: ptrvsrg/file-transfer-server:1.0.0
        container_name: file-transfer-server
        environment:
            SERVER_PORT: ${SERVER_PORT}
        volumes:
            - "./uploads:/file-transfer/uploads"
        networks:
            test-network:
                ipv4_address: 172.21.0.2
    client:
        build:
            context: ./
            dockerfile: ./client.Dockerfile
        image: ptrvsrg/file-transfer-client:1.0.0
        container_name: file-transfer-client
        depends_on:
            - server
        environment:
            SERVER_ADDRESS: 172.21.0.2
            SERVER_PORT: ${SERVER_PORT}
            FILE_NAME: ${FILE_NAME}
        volumes:
            - "./transfer-files:/file-transfer/transfer-files"
        networks:
            test-network:
                ipv4_address: 172.21.0.3
networks:
    test-network:
        ipam:
            driver: default
            config:
                - subnet: 172.21.0.0/16
                  gateway: 172.21.0.1